import mongoose from "mongoose";

const UserSchema=new mongoose.Schema({
    password:{
        type:String,
        // required:true,
    },
    name:{
        type:String,
        required:true,
    },
    domain:{
        type:String,
    },
    cgpa:{
        type:String,
    },
    email:{
        type:String,
        required:true,
        unique:true,
    },
    img:{
        type:String,
    },
    phone:{
        type:String,
        // required:true,
    },
    github:{
        type:String,
    },
    linkedin:{
        type:String,
    },
    leetcode:{
        type:String,
    },
    resume:{
        type:String,
    },
    c_percentage:{
        type:String,
    },
    c_location:{
        type:String,
    },
    accademinDet:{
        type:String,
    },
    collegeName:{
        type:String,
    },
    passingYear:{
        type:Number,
    },
    twelvePercentage:{
        type:Number,
    },
    twelveLocation:{
        type:String,
    },
    tenthLocation:{
        type:String,
    },
    twelvePassingYear:{
        type:String,
    },
    tenthPassingYear:{
        type:String,
    },
    tenthPercentage:{
        type:Number,
    },
    degreePursuing:{
        type:Number,
    },
    project1:{
        type:String,
    },
    project1Dec:{
        type:String,
    },
    project1TechStack:{
        type:String,
    },
    project2TechStack:{
        type:String,
    },
    project3TechStack:{
        type:String,
    },
    project2:{
        type:String,
    },
    project2Dec:{
        type:String,
    },
    project3:{
        type:String,
    },
    Techskill1:{
        type:String,
    },
    Techskill2:{
        type:String,
    },
    Techskill3:{
        type:String,
    },
    Techskill4:{
        type:String,
    },
    Techskill5:{
        type:String,
    },Techskill6:{
        type:String,
    },
    Techskill7:{
        type:String,
    },
    excurr_1:{
        type:String,
    },excurr_2:{
        type:String,
    },
    excurr_3:{
        type:String,
    },
    excurr_4:{
        type:String,
    },
    
    

},{timestamps:true})

export default mongoose.model("Users",UserSchema)